### ISSUE TITLE
Cash HUD Missing

### ISSUE THREAD

**Issue by x0Z3ro0x** [x0Z3ro0x/DKG-FiveM-Server#1]
No errors present. Cash shows in inventory, but not on the main HUD. Need to investigate further to find out why. Predictions are something to do with the custom HUD and our esx_society.

**Comment by AaronF0216** [comment]
Please send me across the files so I can take a look into it and once I find the issue it will be returned.

**Comment by x0Z3ro0x** [comment]
gotta research it online or on a support discord. All esx and essentialmode code matches that of the online githubs and SHOULD display the cash. We can try taking a look at the esx_society script but I'd be more curious to see if there is an update for it before we waste our own time. There are no errors, so it's something stupid simple being looked over because cash still works. It shows up in your F2 as well. Just not on the HUD.

**Comment by x0Z3ro0x** [comment]
Yup there is an update available. I shall throw it in and see what happens.

**Comment by x0Z3ro0x** [comment]
Fixed. Enjoy.
