### ISSUE TITLE
Food not working

### ISSUE THREAD

**Issue by AaronF0216** [x0Z3ro0x/DKG-FiveM-Server#7]
Players cant eat food and have been dying from it.

**Comment by AaronF0216** [comment]
I cant eat food either

**Comment by x0Z3ro0x** [comment]
Just so everyone knows, the rabbit food worked the whole time. You all starved with food 2ft away. This is why everyone hates us Americans.

All other food and drink has been fixed...be warned on that gas station coffee though, that rumor just may be true.
