### ISSUE TITLE
Suggestion?

### ISSUE THREAD

**Issue by CathyJane** [x0Z3ro0x/DKG-FiveM-Server#8]
Hi Zero, could you put in a postal map onto the server? - Cathy

**Comment by x0Z3ro0x** [comment]
Thanks for the awesome suggestion! We have it in now, I just have to get the files started in the config and then of course upload the extra files here should users want to be able to zoom in and what not.

I will make sure to push this through as a ticket and you can track the progress here! Thanks again.

**Comment by CathyJane** [comment]
When is this going to be put in?
